"""Render REFERENCES.md from the formatted Locations JSON batches.

Each venue gets its own section, anchored to match the `references_anchor`
field the Locations tab links to. Every source it came from is one bullet
carrying a clickable link, the source name, and a blurb of what that source
said about that specific spot.

Merges across every batch in parsed/formatted, so re-running after a new
batch lands rebuilds the whole file with the new sources folded in.

Usage:
    python tools/build_references.py
        [--formatted-dir parsed/formatted] [--out REFERENCES.md]
"""

import json
import sys
from pathlib import Path

import click

HEADER = """# References

Provenance for every venue in the **Locations** tab of the Spain 2026 sheet.
Each section is linked from that tab's `References` column.

*Generated by `tools/build_references.py` — edit the source batches in
`parsed/formatted/`, not this file.*
"""


def load_batches(formatted_dir: Path) -> tuple[list[dict], list[str]]:
    """Load every formatted batch, returning (locations, batch_names)."""
    locations, batches = [], []
    for path in sorted(formatted_dir.glob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        locations.extend(payload["locations"])
        batches.append(payload["batch"])
    return locations, batches


# Scalar fields where a later batch's non-empty value supersedes an earlier
# one (batches load in filename order, so later == more recent capture).
_OVERRIDE_FIELDS = (
    "region",
    "neighborhood",
    "type",
    "emoji",
    "description",
    "cost_range",
    "address",
    "latitude",
    "longitude",
    "google_map",
    "rating",
    "geo_note",
)


def _split_tags(tags: str | None) -> set[str]:
    return {t.strip() for t in (tags or "").split(",") if t.strip()}


def _ref_key(ref: dict) -> tuple:
    # Not url alone: two excerpts captured from the same conversation on
    # different days are distinct sources.
    return (ref.get("url"), ref.get("date"), ref.get("note"))


def merge_locations(locations: list[dict]) -> dict[str, dict]:
    """Collapse rows describing the same venue across batches.

    Keyed on the anchor, which is the venue-name slug. A later batch's
    non-empty scalar fields supersede earlier ones, tags and flags union,
    and references append (deduped on url + date + note).
    """
    merged: dict[str, dict] = {}
    for row in locations:
        key = row["references_anchor"]
        if key not in merged:
            merged[key] = {**row, "references": list(row["references"])}
            continue
        current = merged[key]
        for field in _OVERRIDE_FIELDS:
            value = row.get(field)
            if value not in (None, ""):
                current[field] = value
        current["tags"] = ", ".join(
            sorted(_split_tags(current.get("tags")) | _split_tags(row.get("tags")))
        )
        current["flags"] = sorted(
            set(current.get("flags") or []) | set(row.get("flags") or [])
        )
        seen = {_ref_key(r) for r in current["references"]}
        for ref in row["references"]:
            if _ref_key(ref) not in seen:
                current["references"].append(ref)
                seen.add(_ref_key(ref))
    return merged


def format_instagram_reference(ref: dict) -> str:
    """Render an Instagram source (shortcode + creator + engagement)."""
    creator = ref.get("creator") or ref.get("handle", "")
    handle = ref.get("handle", "")
    who = f"{creator} ({handle})" if creator and handle else creator or handle
    stats = []
    if ref.get("posted"):
        stats.append(ref["posted"])
    if ref.get("views"):
        stats.append(f"{ref['views']:,} views")
    if ref.get("likes"):
        stats.append(f"{ref['likes']:,} likes")
    meta = f" · {' · '.join(stats)}" if stats else ""
    return f"- **Instagram — {who}**{meta} · [{ref['shortcode']}]({ref['url']})"


def format_generic_reference(ref: dict) -> str:
    """Render a non-Instagram source (Gemini, blog, article, …).

    Expects ``source`` (label), ``url``, and optional ``date``.
    """
    source = ref.get("source", "Source")
    date = f" · {ref['date']}" if ref.get("date") else ""
    link = f" · [link]({ref['url']})" if ref.get("url") else ""
    return f"- **{source}**{date}{link}"


def format_reference(ref: dict) -> str:
    """Render one source as a markdown bullet, dispatching on its shape."""
    if ref.get("shortcode"):
        bullet = format_instagram_reference(ref)
    else:
        bullet = format_generic_reference(ref)
    if ref.get("note"):
        bullet += f"\n  - {ref['note']}"
    return bullet


def format_venue(row: dict) -> str:
    """Render one venue section."""
    anchor = row["references_anchor"].split("#", 1)[-1]
    # Both id and name: GitHub's sanitizer honors `name` on anchor tags, while
    # local markdown viewers key off `id`. The explicit anchor also decouples us
    # from GitHub's auto-generated heading slugs, which drop apostrophes and
    # emoji and so would not match our slugify() output.
    lines = [
        f'<a id="{anchor}" name="{anchor}"></a>',
        "",
        f"## {row['emoji']} {row['name']}",
        "",
    ]

    facts = [
        f"**Region:** {row['region']}",
        f"**Neighborhood:** {row['neighborhood']}",
        f"**Type:** {row['type']}",
        f"**Rating:** {row['rating']}/5",
    ]
    if row.get("cost_range"):
        facts.append(f"**Cost:** {row['cost_range']}")
    lines.append(" · ".join(facts))
    lines.append("")

    if row.get("google_map"):
        lines.append(f"[Google Maps]({row['google_map']})")
        lines.append("")

    if row.get("geo_note"):
        lines.append(f"> ⚠️ **Approximate location** — {row['geo_note']}")
        lines.append("")

    lines.append(f"### Sources ({len(row['references'])})")
    lines.append("")
    for ref in sorted(row["references"], key=lambda r: r.get("posted", "")):
        lines.append(format_reference(ref))
    lines.append("")
    return "\n".join(lines)


@click.command()
@click.option(
    "--formatted-dir",
    default="parsed/formatted",
    type=click.Path(exists=True, path_type=Path),
    help="Directory of formatted batch JSON files.",
)
@click.option(
    "--out",
    default="REFERENCES.md",
    type=click.Path(path_type=Path),
    help="Markdown file to write.",
)
def main(formatted_dir: Path, out: Path) -> None:
    """Rebuild REFERENCES.md from every formatted batch."""
    for stream in (sys.stdout, sys.stderr):
        stream.reconfigure(encoding="utf-8", errors="replace")

    locations, batches = load_batches(formatted_dir)
    if not locations:
        raise click.ClickException(f"No formatted batches found in {formatted_dir}")

    merged = merge_locations(locations)
    # Highest-rated first, then alphabetical, so the must-gos read first.
    ordered = sorted(merged.values(), key=lambda r: (-r["rating"], r["name"].lower()))

    sections = [HEADER, "", f"*Batches included: {', '.join(batches)}*", ""]
    sections.append(f"*{len(ordered)} venues · "
                    f"{sum(len(r['references']) for r in ordered)} sources*")
    sections.append("")
    sections.append("---")
    sections.append("")
    for row in ordered:
        sections.append(format_venue(row))
        sections.append("---")
        sections.append("")

    out.write_text("\n".join(sections).rstrip() + "\n", encoding="utf-8")
    click.echo(f"Wrote {len(ordered)} venue sections "
               f"({sum(len(r['references']) for r in ordered)} sources) to {out}")


if __name__ == "__main__":
    main()
